# Copyright 2022 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically generation from ./hack/update-workflows.sh

name: 'knative-sandbox/control-protocol'

on:
  schedule:
    - cron: '0 1 * * 1-5' # 6am Pacific, weekdays.

  workflow_dispatch:
    inputs:
      release:
        type: string
        required: false
        description: Release Version

jobs:
  releasability:
    uses: ./.github/workflows/releasability.yaml
    with:
      repo: knative-sandbox/control-protocol
      release: ${{ inputs.release }}
    secrets: inherit
